# Hadolint configuration to suppress specific warnings
# DL3008: Pin versions in apt get install - now properly pinned
# DL3013: Pin pip version - already pinned in Dockerfile
ignore:
  - DL3013  # Suppress pip version pinning (already pinned to 24.3.1)
