name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.4.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install
      
      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "Released version: $VERSION"
      
      - name: Update version in files
        run: |
          VERSION="${{ steps.version.outputs.VERSION_NUMBER }}"
          
          # Update package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
          
          # Update README.md version
          sed -i "s/Current Version: \*\*.*\*\*/Current Version: **$VERSION**/" readme.md
          
          # Update app.py version
          sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" app.py
          sed -i "s/__version_info__ = ([0-9]+, [0-9]+, [0-9]+)/__version_info__ = (${VERSION//./, })/" app.py
          
          # Update unraid template version (multiple locations)
          sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/" unraid-template.xml
          sed -i -E "s/Docker Template Manager v[0-9]+\.[0-9]+\.[0-9]+/Docker Template Manager v$VERSION/" unraid-template.xml
          sed -i -E "s/\*\*Version [0-9]+\.[0-9]+\.[0-9]+\*\*/**Version $VERSION**/" unraid-template.xml
          
          # Update HTML migration guides version
          sed -i -E "s/<strong>Version:<\/strong> [0-9]+\.[0-9]+\.[0-9]+/<strong>Version:<\/strong> $VERSION/" static/folder-to-vdisk.html
          sed -i -E "s/<strong>Version:<\/strong> [0-9]+\.[0-9]+\.[0-9]+/<strong>Version:<\/strong> $VERSION/" static/vdisk-to-folder.html
          
          echo "Updated version to $VERSION in all files"
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
            type=raw,value=${{ steps.version.outputs.VERSION_NUMBER }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Docker Template Manager ${{ steps.version.outputs.VERSION }}
          body: |
            ## 🚀 What's New in ${{ steps.version.outputs.VERSION }}
            
            ### ✨ New Features
            - Professional UI with theme toggle
            - Sortable tables across all sections
            - Hybrid template editor (form + XML)
            - Bulk operations for templates, containers, and backups
            - Migration guides integration
            - Mobile responsive design
            
            ### 🔧 Improvements
            - Standardized look and feel across all sections
            - Enhanced container management
            - Improved backup system
            - Better error handling and user feedback
            
            ### 🐛 Bug Fixes
            - Fixed template editor form data loading
            - Resolved logo sizing issues
            - Improved modal layouts
            - Enhanced button consistency
            
            ## 📦 Installation
            
            ### Docker Compose
            ```yaml
            services:
              docker-template-manager:
                image: ghcr.io/qballjos/docker-template-manager:${{ steps.version.outputs.VERSION_NUMBER }}
                container_name: docker-template-manager
                ports:
                  - "8889:8889"
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock:ro
                  - /boot/config/plugins/dockerMan/templates-user:/templates:rw
                  - /mnt/user/appdata/docker-template-manager/backups:/backups:rw
                  - /mnt/user/appdata/docker-template-manager/config:/config:rw
                environment:
                  - API_KEY=your-secure-api-key
                  - TZ=Europe/Amsterdam
                restart: unless-stopped
            ```
            
            ### Docker Run
            ```bash
            docker run -d \
              --name docker-template-manager \
              -p 8889:8889 \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /boot/config/plugins/dockerMan/templates-user:/templates:rw \
              -v /mnt/user/appdata/docker-template-manager/backups:/backups:rw \
              -v /mnt/user/appdata/docker-template-manager/config:/config:rw \
              -e API_KEY=your-secure-api-key \
              -e TZ=Europe/Amsterdam \
              --restart unless-stopped \
              ghcr.io/qballjos/docker-template-manager:${{ steps.version.outputs.VERSION_NUMBER }}
            ```
            
            ## 🔄 Update Instructions
            
            To update from a previous version:
            1. Stop the current container: `docker stop docker-template-manager`
            2. Remove the old container: `docker rm docker-template-manager`
            3. Pull the new image: `docker pull ghcr.io/qballjos/docker-template-manager:${{ steps.version.outputs.VERSION_NUMBER }}`
            4. Start with the new image using the commands above
            
            ## 📋 Changelog
            
            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
            
            ## 🆘 Support
            
            - 📖 [Documentation](https://github.com/qballjos/docker-template-manager#readme)
            - 🐛 [Report Issues](https://github.com/qballjos/docker-template-manager/issues)
            - 💬 [Discussions](https://github.com/qballjos/docker-template-manager/discussions)
          files: |
            README.md
            CHANGELOG.md
            unraid-template.xml
            docker-compose.yml
            docker-compose.local.yml
          draft: false
          prerelease: false
      
      - name: Commit version updates to repository
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all modified files
          git add app.py package.json readme.md unraid-template.xml static/folder-to-vdisk.html static/vdisk-to-folder.html
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No version changes to commit"
          else
            # Commit the changes
            git commit -m "chore: update version to ${{ steps.version.outputs.VERSION_NUMBER }} [skip ci]"
            
            # Push the changes
            git push origin main
            echo "Version updated to ${{ steps.version.outputs.VERSION_NUMBER }} and committed to repository"
          fi
